name: dart_function_analyzer
description: Ferramenta para analisar dependências de funções em projetos Dart/Flutter
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  args: ^2.4.0
  path: ^1.8.3
  collection: ^1.17.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0